server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # Auth Service Routes - now preserving the /auth/ prefix
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        # Document Service Routes
        - id: document-service
          uri: http://localhost:8082
          predicates:
            - Path=/documents/**, /categories/**, /departments/**

        # Translation Service Routes 
        - id: translation-service-direct
          uri: http://localhost:8083
          predicates:
            - Path=/api/translate/**

        # Storage Service Routes
        - id: storage-service
          uri: http://localhost:8090
          predicates:
            - Path=/storage/**

# JWT Configuration
jwt:
  secret: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789AB
  expiration: 86400000 # 24 hours in milliseconds

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always