server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: document-service
          uri: http://localhost:8082
          predicates:
            - Path=/documents/**

        - id: category-service
          uri: http://localhost:8082
          predicates:
            - Path=/categories/**

        - id: department-service
          uri: http://localhost:8082
          predicates:
            - Path=/departments/**

        - id: translation-service
          uri: http://localhost:9083
          predicates:
            - Path=/api/translate/**

        - id: storage-service
          uri: http://localhost:8090
          predicates:
            - Path=/storage/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**   
        - id: document-service-dashboard   
          uri: http://localhost:8082       
          predicates:
            - Path=/dashboard


        

jwt:
  secret: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789AB
  expiration: 86400000

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
